spring.application.name=booksocial
logging.level.org.springframework.security=DEBUG
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/booksocial
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
#Tự động cập nhật cấu trúc cơ sở dữ lệu mỗi khi ứng dụng khởi động
spring.jpa.hibernate.ddl-auto=update

#Show các câu lệnh SQL mà Hibernate tự động tạo ra và thực thi
spring.jpa.show-sql=true

#Cấu hình jwt
jwt.secret=038esjdnsm,nc9328e0912piwsmnsdk@!^@(*@*
jwt.expiration=86400000

#Cloudinary
cloudinary.cloud-name=du0quuvbl
cloudinary.api-key=385618194935568
cloudinary.api-secret=9jKqT5pDtyli3_ory4-jy8fkjTo

#Pagination
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

#Google Gemini AI
spring.ai.google.genai.api-key=AQ.Ab8RN6LLbAHsY0MiKQJCoLqvojgU4hxxjLwJ7gRXc1OGcTS7PA
spring.ai.google.genai.chat.model=gemini-3.6-flash

//Login google
#spring.security.oauth2.client.registration.google.client-id=620077251730-71efp8imk88epphavtc04ejobd4rsjuf.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
google.client.id=620077251730-71efp8imk88epphavtc04ejobd4rsjuf.apps.googleusercontent.com

