spring.application.name=booksocial

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/booksocial
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
#Tự động cập nhật cấu trúc cơ sở dữ lệu mỗi khi ứng dụng khởi động
spring.jpa.hibernate.ddl-auto=update

#Show các câu lệnh SQL mà Hibernate tự động tạo ra và thực thi
spring.jpa.show-sql=true
